"""init schema

Revision ID: 0f96f4cc410b
Revises: 
Create Date: 2025-11-01 14:08:11.127277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '0f96f4cc410b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector";')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cluster_centroid_ann', 'cluster', ['centroid'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': '50'}, postgresql_ops={'centroid': 'vector_cosine_ops'})
    op.create_table('rss_feed',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('leaning', postgresql.ENUM('LEFT', 'CENTER', 'RIGHT', name='leaning_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    op.create_table('article',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('scraped_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feed.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_article_url')
    )
    op.create_index('idx_article_cluster_id', 'article', ['cluster_id'], unique=False)
    op.create_index('idx_article_embedding_ann', 'article', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': '100'}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_article_feed_id', 'article', ['feed_id'], unique=False)
    op.create_index('idx_article_published_at', 'article', ['published_at'], unique=False)
    op.create_table('summary',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('leaning', postgresql.ENUM('LEFT', 'CENTER', 'RIGHT', name='leaning_enum'), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('summarized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'leaning', name='uq_summary_cluster_leaning')
    )
    op.create_index('idx_summary_cluster_id', 'summary', ['cluster_id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'image_url', name='uq_image_article_url')
    )
    op.create_index('idx_image_article_id', 'image', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_image_article_id', table_name='image')
    op.drop_table('image')
    op.drop_index('idx_summary_cluster_id', table_name='summary')
    op.drop_table('summary')
    op.drop_index('idx_article_published_at', table_name='article')
    op.drop_index('idx_article_feed_id', table_name='article')
    op.drop_index('idx_article_embedding_ann', table_name='article', postgresql_using='ivfflat', postgresql_with={'lists': '100'}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_article_cluster_id', table_name='article')
    op.drop_table('article')
    op.drop_table('rss_feed')
    op.drop_index('idx_cluster_centroid_ann', table_name='cluster', postgresql_using='ivfflat', postgresql_with={'lists': '50'}, postgresql_ops={'centroid': 'vector_cosine_ops'})
    op.drop_table('cluster')
    # ### end Alembic commands ###
